apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pv-claim
  namespace: chat-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
