apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: chat-app
spec:
  selector:
    app: mysql       # Must match the label in the StatefulSet
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP